CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;

CREATE TABLE "Citizens" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Fid" integer NOT NULL,
    "StreetName" text NOT NULL,
    "BuildingNumber" text NOT NULL,
    "FlatNumber" text NOT NULL,
    "FirstName" text NOT NULL,
    "LastName" text NOT NULL,
    "FamilyNumber" integer NOT NULL,
    "IsLonely" boolean NOT NULL,
    "IsAddressWrong" boolean NOT NULL,
    "NewStreetName" text,
    "NewBuildingNumber" text,
    "NewFlatNumber" text,
    "StatusInCallCenter" text NOT NULL,
    "Phone1" text,
    "Phone2" text,
    "Phone3" text,
    "IsAnsweredTheCall" boolean NOT NULL,
    "HasMamad" boolean NOT NULL,
    "HasMiklatPrati" boolean NOT NULL,
    "HasMiklatZiburi" boolean NOT NULL,
    "HasMobilityRestriction" boolean NOT NULL,
    "IsDead" boolean NOT NULL,
    "IsLeftTheCity" boolean NOT NULL,
    "HasTemporaryAddress" boolean NOT NULL,
    "IsTemporaryAbroad" boolean NOT NULL,
    "TemporaryStreetName" text,
    "TemporaryBuildingNumber" text,
    "TemporaryFlat" text,
    "LockedByUserId" uuid,
    "LockedUntil" timestamp with time zone,
    "LastUpdatedAt" timestamp with time zone,
    "CreatedAt" timestamp with time zone NOT NULL,
    "LastUpdatedByUserId" uuid,
    "AppearanceCount" integer NOT NULL,
    "FirstTimeAppearance" timestamp with time zone,
    "SecondTimeAppearance" timestamp with time zone,
    "ThirdTimeAppearance" timestamp with time zone,
    CONSTRAINT "PK_Citizens" PRIMARY KEY ("Id")
);

CREATE TABLE "Users" (
    "Id" uuid NOT NULL,
    "Username" text NOT NULL,
    "PasswordHash" text NOT NULL,
    "Role" text NOT NULL,
    CONSTRAINT "PK_Users" PRIMARY KEY ("Id")
);

CREATE TABLE "CallcenterCases" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "CallcenterCaseNumber" character varying(100) NOT NULL,
    "CitizenRecordId" integer NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone,
    CONSTRAINT "PK_CallcenterCases" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_CallcenterCases_Citizens_CitizenRecordId" FOREIGN KEY ("CitizenRecordId") REFERENCES "Citizens" ("Id") ON DELETE CASCADE
);

CREATE UNIQUE INDEX "IX_CallcenterCases_CitizenRecordId" ON "CallcenterCases" ("CitizenRecordId");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20250624054149_Initial', '8.0.17');

COMMIT;

