CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;

CREATE TABLE "Citizens" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Fid" integer NOT NULL,
    "StreetName" text NOT NULL,
    "BuildingNumber" text NOT NULL,
    "FlatNumber" text NOT NULL,
    "FirstName" text NOT NULL,
    "LastName" text NOT NULL,
    "FamilyNumber" integer NOT NULL,
    "IsLonely" boolean NOT NULL,
    "IsAddressWrong" boolean NOT NULL,
    "NewStreetName" text,
    "NewBuildingNumber" text,
    "NewFlatNumber" text,
    "StatusInCallCenter" text NOT NULL,
    "Phone1" text,
    "Phone2" text,
    "Phone3" text,
    "IsAnsweredTheCall" boolean NOT NULL,
    "HasMamad" boolean NOT NULL,
    "HasMiklatPrati" boolean NOT NULL,
    "HasMiklatZiburi" boolean NOT NULL,
    "HasMobilityRestriction" boolean NOT NULL,
    "IsDead" boolean NOT NULL,
    "IsLeftTheCity" boolean NOT NULL,
    "HasTemporaryAddress" boolean NOT NULL,
    "IsTemporaryAbroad" boolean NOT NULL,
    "TemporaryStreetName" text,
    "TemporaryBuildingNumber" text,
    "TemporaryFlat" text,
    "LockedByUserId" uuid,
    "LockedUntil" timestamp with time zone,
    "LastUpdatedAt" timestamp with time zone,
    "CreatedAt" timestamp with time zone NOT NULL,
    "LastUpdatedByUserId" uuid,
    "AppearanceCount" integer NOT NULL,
    CONSTRAINT "PK_Citizens" PRIMARY KEY ("Id")
);

CREATE TABLE "Users" (
    "Id" uuid NOT NULL,
    "Username" text NOT NULL,
    "PasswordHash" text NOT NULL,
    "Role" text NOT NULL,
    CONSTRAINT "PK_Users" PRIMARY KEY ("Id")
);

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20250622171612_Initial', '8.0.17');

COMMIT;

